### ISSUE TITLE
Contact page, email button text ???

### ISSUE THREAD

**Issue by Smoreley** [Smoreley/collab-w1-d4#10]
On the contact page the email button does not have text in it or the text is unreadable.

**Comment by dev-4** [comment]
I hope Emma fixes it, if not then I will try to fix it when I get home

**Comment by ejliberman** [comment]
I'll be able to look at it when I get back home in an hour or so.

**Comment by dev-4** [comment]
I don't know if it was me or someone else but this issue has been resolved.
