### ISSUE TITLE
Indents and nests

### ISSUE THREAD

**Issue by dev-4** [Smoreley/collab-w1-d4#5]
Whenever you make changes, make sure to indent and nest everything properly or let me know to do it
This issue is going to be the last one on the list because cleaning the indents and nests are not required yet (but preferred)

**Comment by dev-4** [comment]
This issue is going to be the last one on the list because cleaning the indents and nests are not required (but preferred)

**Comment by Smoreley** [comment]
Certainly an issue but I do not think it is one that should be posted here. Reason being that it is not something that can be checked off and completed. It's a never-ending challenge of keeping the code organized.
